# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df11a41f8c3eca4ec16450aace535a170154b8c6b8d4364a65d963c065fd055a63c9adc5bbf3d6fbde77ffcd1d6f67a9373042e0bccf2a9a4832ac7b37ff8c5

test:
  secret_key_base: 1f58c59b0affba7b68d4e9c8c28bdcadd29a554c9b1542a1bca85c75cd80021e833416371870528af576ecd0b1eb09172d76618e3b87c99f75f39c913b89d9f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
